FROM node:22-alpine AS base

WORKDIR /app

RUN apk add --no-cache dumb-init

COPY prisma.config.ts ./
COPY prisma ./prisma/

COPY worker/package*.json ./
COPY worker/tsconfig.json ./
RUN npm install
COPY worker/ ./

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["npm", "run", "dev"]
