FROM node:22-alpine AS base

WORKDIR /app

RUN apk add --no-cache dumb-init

COPY prisma.config.ts ./
COPY prisma ./prisma/

COPY server/package*.json ./
COPY server/tsconfig.json ./
RUN npm install
COPY server/ ./

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["npm", "run", "dev"]
