FROM node:22-alpine AS base

WORKDIR /app

RUN apk add --no-cache dumb-init

COPY prisma.config.ts ./
COPY prisma ./prisma/

COPY scheduler/package*.json ./
COPY scheduler/tsconfig.json ./
RUN npm install

COPY scheduler/ ./

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["npm", "run", "dev"]